<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Guru V1" duration-ms="24" started-at="2023-12-28T10:15:30Z" finished-at="2023-12-28T10:15:30Z">
    <groups>
    </groups>
    <test name="com.guruv1.login" duration-ms="24" started-at="2023-12-28T10:15:30Z" finished-at="2023-12-28T10:15:30Z">
      <class name="com.guruv1.login.Login01_CreateAccountAndLogin">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.guruv1.login.Login01_CreateAccountAndLogin@7946e1f4]" name="beforeClass" is-config="true" duration-ms="4" started-at="2023-12-28T17:15:30Z" finished-at="2023-12-28T17:15:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="TC01_CreateAnAcount()[pri:0, instance:com.guruv1.login.Login01_CreateAccountAndLogin@7946e1f4]" name="TC01_CreateAnAcount" duration-ms="4" started-at="2023-12-28T17:15:30Z" finished-at="2023-12-28T17:15:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_CreateAnAcount -->
        <test-method status="FAIL" signature="TC02_Login()[pri:0, instance:com.guruv1.login.Login01_CreateAccountAndLogin@7946e1f4]" name="TC02_Login" duration-ms="3" started-at="2023-12-28T17:15:30Z" finished-at="2023-12-28T17:15:30Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.guruv1.login.Login01_CreateAccountAndLogin.TC02_Login(Login01_CreateAccountAndLogin.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02_Login -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.guruv1.login.Login01_CreateAccountAndLogin@7946e1f4]" name="afterClass" is-config="true" duration-ms="0" started-at="2023-12-28T17:15:30Z" finished-at="2023-12-28T17:15:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.guruv1.login.Login01_CreateAccountAndLogin -->
    </test> <!-- com.guruv1.login -->
  </suite> <!-- Guru V1 -->
</testng-results>
